#spring.datasource.url=jdbc:h2:mem:testdb

#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

#server.port=${PORT:8080}
######################################
SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d71m7dua2pns73f9v240-a:5432/employee_db_6fab
SPRING_DATASOURCE_USERNAME=employee_db_6fab_user
SPRING_DATASOURCE_PASSWORD=1R60NGxqV65e9fXyZuz75aZTYSMPtslB
spring.jpa.hibernate.ddl-auto=update



spring.jpa.show-sql=true